theme: jekyll-theme-minimal
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
 # - jekyll-remote-theme
title: Rabisankar Samanta
#description: md.islam@uni-a.de
description: <a href="mailto:rabisankar.samanta@nyulangone.org">rabisankar.samanta@nyulangone.org</a>
description: <a href="mailto:rabisankar.samanta96@gmail.com">rabisankar.samanta96@gmail.com</a>
#logo: /assets/img/logo.png
# Hide GitHub footer links
#show_downloads: true
#github:
 # is_project_page: false
